/* About this report: scan metadata and how to regenerate it. */
section({
  id: 'about', title: 'About this report',
  render: function (el) {
    var m = MANIFEST || {};
    var g = G.project.git || {};
    el.innerHTML = '<h1>About this report</h1><p class="lead">Generated by static analysis. No code from the project was executed, and nothing was sent anywhere.</p>' +
      '<div class="grid g2"><div class="card"><h3>Scan</h3><dl class="kv">' +
      '<dt>Generated</dt><dd>' + esc(new Date(G.project.scannedAt).toLocaleString()) + '</dd>' +
      '<dt>Generator</dt><dd>RepoFlow ' + esc(G.generator.version) + ' · schema ' + esc(G.schemaVersion) + '</dd>' +
      (g.commit ? '<dt>Git</dt><dd><code>' + esc(g.commit) + '</code>' + (g.branch ? ' on ' + esc(g.branch) : '') + '</dd>' : '') +
      (m.files ? '<dt>Files</dt><dd>' + fmt(m.files.listed) + ' listed, ' + fmt(m.files.parsed) + ' parsed</dd>' : '') +
      (m.durationMs != null ? '<dt>Duration</dt><dd>' + (m.durationMs / 1000).toFixed(1) + ' s</dd>' : '') +
      (m.excluded ? '<dt>Excluded</dt><dd class="small">' + m.excluded.map(function (x) { return '<code>' + esc(x) + '/</code>'; }).join(' ') + ', .gitignore entries, dependencies and build output</dd>' : '') +
      '</dl></div><div class="card"><h3>Regenerate</h3><p class="small" style="margin-top:0">From the project root:</p><p><code>npx repoflow scan .</code></p>' +
      '<p class="small muted">Files next to this page: <code>project-graph.json</code> (the normalized graph), <code>project-summary.md</code>, <code>scan-manifest.json</code>.</p></div></div>' +
      '<h2>Adapters used</h2><div class="table-wrap"><table><thead><tr><th>Framework</th><th>Root</th><th>Confidence</th><th>Evidence</th></tr></thead><tbody>' +
      G.frameworks.map(function (f) { return '<tr><td><b>' + esc(f.name) + '</b>' + (f.version ? ' ' + esc(f.version) : '') + '</td><td><code>' + esc(f.root) + '</code></td><td>' + Math.round(f.confidence * 100) + '%</td><td class="small">' + f.evidence.map(esc).join('<br>') + '</td></tr>'; }).join('') +
      '</tbody></table></div>' +
      (G.warnings.length ? '<h2>Warnings</h2><ul>' + G.warnings.map(function (w) { return '<li>' + esc(w) + '</li>'; }).join('') + '</ul>' : '') +
      '<h2>Limits of static analysis</h2><ul class="small"><li>Routes registered dynamically (loops, database-driven routes, plugins) may be missing.</li><li>Steps, data access and view variables are detected from code patterns and can miss indirect calls.</li><li>Relationships marked as inferred come from column names, not declared foreign keys.</li><li>Findings are heuristics to verify, not proof of a vulnerability.</li></ul>';
  }
});
