/** project-summary.md: a plain-text digest of the graph for code review, chat and diffs. */
import { ProjectGraph } from '../schema/graph';

function cell(s: string | number | undefined): string {
  return String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

export function renderSummary(g: ProjectGraph): string {
  const out: string[] = [];
  const s = g.stats;
  const fws = g.frameworks.filter((f) => f.id !== 'generic');
  out.push(`# ${g.project.name}: project summary`, '');
  out.push(`Generated by RepoFlow ${g.generator.version} on ${g.project.scannedAt.slice(0, 10)}${g.project.git?.commit ? ` at commit \`${g.project.git.commit.slice(0, 7)}\`` : ''}. Open \`index.html\` in this folder for the interactive explorer.`, '');
  if (g.project.description) out.push(g.project.description, '');

  out.push('## At a glance', '');
  out.push('| Files | Lines | Routes | Handlers | Models | Tables | Views | Integrations | Findings |', '|---|---|---|---|---|---|---|---|---|');
  out.push(`| ${s.files} | ${s.lines} | ${s.routes} | ${s.handlers} | ${s.models} | ${s.tables} | ${s.views} | ${s.integrations} | ${s.findings} |`, '');

  out.push('## Technology', '');
  for (const f of fws) out.push(`- **${f.name}**${f.version ? ` ${f.version}` : ''} (${f.language}) in \`${f.root === '.' ? './' : f.root + '/'}\``);
  if (!fws.length) out.push('- No supported framework detected.');
  const langs = g.languages.slice(0, 6).map((l) => `${l.name} (${l.files} files, ${l.lines} lines)`).join(', ');
  if (langs) out.push(`- Languages: ${langs}`);
  out.push('');

  if (g.lifecycle.length) {
    out.push('## How a request works', '');
    g.lifecycle.forEach((st, i) => out.push(`${i + 1}. **${st.title}**${st.subtitle ? ` (${st.subtitle})` : ''}: ${st.detail}`));
    out.push('');
  }

  if (g.routes.length) {
    out.push(`## Routes (${g.routes.length})`, '');
    out.push('| Method | Path | Handler | Middleware | Tables |', '|---|---|---|---|---|');
    const handlers = new Map(g.handlers.map((h) => [h.id, h]));
    for (const r of g.routes.slice(0, 400)) {
      const h = r.handler ? handlers.get(r.handler) : undefined;
      out.push(`| ${r.method} | \`${cell(r.path)}\` | ${cell(r.target)} | ${cell(r.middleware.join(', '))} | ${cell(h?.tables.join(', '))} |`);
    }
    if (g.routes.length > 400) out.push('', `…and ${g.routes.length - 400} more (see project-graph.json).`);
    out.push('');
  }

  if (g.tables.length || g.models.length) {
    out.push(`## Data (${g.models.length} models, ${g.tables.length} tables)`, '');
    for (const t of g.tables.slice(0, 200)) {
      const fks = t.foreignKeys.map((f) => `${f.column} → ${f.references}${f.inferred ? ' (inferred)' : ''}`).join('; ');
      out.push(`- \`${t.name}\`: ${t.columns.length} columns, read by ${t.readBy.length}, written by ${t.writtenBy.length}${fks ? `. FKs: ${fks}` : ''}`);
    }
    out.push('');
  }

  if (g.integrations.length) {
    out.push('## Integrations', '');
    for (const i of g.integrations) out.push(`- **${i.name}** (${i.category}): ${i.evidence.slice(0, 2).map((e) => `\`${e.file}${e.line ? ':' + e.line : ''}\``).join(', ')}`);
    out.push('');
  }

  out.push(`## Findings (${g.findings.length})`, '');
  if (!g.findings.length) out.push('None of the heuristic checks matched.');
  out.push('Heuristic static checks: verify each one in the code.', '');
  for (const f of g.findings.slice(0, 150)) out.push(`- **${f.severity.toUpperCase()}** ${f.title}${f.file ? ` (\`${f.file}${f.line ? ':' + f.line : ''}\`)` : ''}`);
  out.push('');

  if (g.warnings.length) {
    out.push('## Scan warnings', '');
    for (const w of g.warnings) out.push(`- ${w}`);
    out.push('');
  }
  return out.join('\n');
}
